[package]
name = "flint"
version.workspace = true
edition.workspace = true
description = "Flint — Fleet GitOps YAML linter and language server"

[[bin]]
name = "flint"
path = "src/main.rs"

[dependencies]
flint-lint = { path = "../crates/flint-lint" }
flint-lsp = { path = "../crates/flint-lsp" }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
colored = { workspace = true }
ureq = { workspace = true }
quick-xml = { workspace = true }
tempfile = { workspace = true }

[build-dependencies]
chrono = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
