//! `flint hooks` — install/uninstall git hooks for flint validation.

use crate::args::HooksAction;
use anyhow::Result;
use std::path::PathBuf;

pub(crate) fn run(action: HooksAction) -> Result<()> {
    match action {
        HooksAction::Install {
            force,
            strict,
            json,
            pre_push,
        } => {
            if pre_push {
                install_pre_push_hook(force)
            } else {
                install_pre_commit_hook(force, strict, json)
            }
        }
        HooksAction::Uninstall => uninstall_pre_commit_hook(),
    }
}

/// Install a blocking `pre-push` hook that runs the local dry-run over the
/// whole repo. Push is aborted if the dry-run finds blocking issues.
fn install_pre_push_hook(force: bool) -> Result<()> {
    use colored::Colorize;
    use std::os::unix::fs::PermissionsExt;

    let hooks_dir = find_git_hooks_dir()?;
    std::fs::create_dir_all(&hooks_dir)?;
    let hook_path = hooks_dir.join("pre-push");

    if hook_path.exists() && !force {
        let existing = std::fs::read_to_string(&hook_path).unwrap_or_default();
        if existing.contains("flint pre-push hook") {
            println!(
                "{} flint pre-push hook already installed at {}\n  Re-run with --force to overwrite.",
                "ℹ".blue(),
                hook_path.display()
            );
            return Ok(());
        }
        anyhow::bail!(
            "A pre-push hook already exists at {} and was not authored by flint.\nRe-run with --force to overwrite, or move it aside first.",
            hook_path.display()
        );
    }

    let script = r#"#!/bin/sh
# flint pre-push hook (generated by `flint hooks install --pre-push`)
#
# Runs the local dry-run (`flint dry-run .`) over the whole repo before every
# push. If it finds blocking issues the push is aborted — catching gitops
# dry-run failures before they reach the pipeline.
#
# Bypass once: git push --no-verify   •   Remove: flint hooks uninstall

if ! command -v flint >/dev/null 2>&1; then
    echo "flint: pre-push hook installed but 'flint' not found on PATH — skipping" >&2
    exit 0
fi

echo "flint: running local dry-run before push…"
if ! flint dry-run .; then
    echo "" >&2
    echo "flint: local dry-run failed — push blocked." >&2
    echo "  • Bypass once: git push --no-verify" >&2
    exit 1
fi
exit 0
"#;

    std::fs::write(&hook_path, script)?;
    let mut perms = std::fs::metadata(&hook_path)?.permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(&hook_path, perms)?;

    println!(
        "{} Installed flint pre-push hook at {} (blocks push on dry-run failure)",
        "✓".green(),
        hook_path.display()
    );
    println!("  • Bypass once: git push --no-verify");
    Ok(())
}

/// Generate the pre-commit hook script tailored to the install flags.
///
/// - `strict = false` (default): non-blocking. flint runs with `--hook-mode`
///   and the script always exits 0 — diagnostics print but commits never block.
/// - `strict = true`: errors block the commit. flint runs without
///   `--hook-mode` so its native exit code propagates; on failure the script
///   prints a hint about `--no-verify` and exits 1.
/// - `json = true`: flint emits JSON diagnostics (`--format json`). Useful for
///   piping into other tools or CI logs.
fn build_pre_commit_script(strict: bool, json: bool) -> String {
    // Marker string used by `hooks uninstall` to detect a flint-authored hook.
    let header = "# flint pre-commit hook (generated by `flint hooks install`)";

    let format_flag = if json { " --format=json" } else { "" };
    // Non-strict mode uses --hook-mode so flint always exits 0.
    let hook_mode_flag = if strict { "" } else { " --hook-mode" };

    let banner = if strict {
        "flint: running pre-commit validation (strict — errors will block commits)"
    } else {
        "flint: running pre-commit validation (warnings only, never blocks)"
    };

    let on_fail = if strict {
        // Errors block. Print a hint then propagate.
        r#"echo ""  >&2
        echo "flint: errors found — commit blocked." >&2
        echo "  • Bypass once: git commit --no-verify" >&2
        echo "  • Switch to non-blocking: flint hooks install --force" >&2
        exit 1"#
    } else {
        ":  # informational only — never block"
    };

    format!(
        r#"#!/bin/sh
{header}
#
# Runs `flint check --staged{format_flag}{hook_mode_flag}` once when you
# `git commit`: analysis is repo-wide (so cross-file rules — broken
# references, orphans, case collisions — actually run), but only findings
# touching YOUR staged files block. Pre-existing findings elsewhere are a
# context count. Renamed files stay in scope via --no-renames inside flint.
# Strict mode: {strict}. JSON output: {json}.
#
# Remove with: flint hooks uninstall

set -e

if ! command -v flint >/dev/null 2>&1; then
    echo "flint: pre-commit hook installed but 'flint' not found on PATH — skipping" >&2
    exit 0
fi

echo "{banner}"

fail_marker="$(mktemp)"
trap 'rm -f "$fail_marker"' EXIT

flint check --staged{format_flag}{hook_mode_flag} . || echo 1 > "$fail_marker"

if [ -s "$fail_marker" ]; then
    {on_fail}
fi

exit 0
"#,
        header = header,
        format_flag = format_flag,
        hook_mode_flag = hook_mode_flag,
        banner = banner,
        strict = strict,
        json = json,
        on_fail = on_fail,
    )
}

/// Locate the `.git/hooks/` directory for the current repo.
///
/// Walks up from the current working directory looking for a `.git` entry.
/// Errors out with a clear message if not in a git repo.
fn find_git_hooks_dir() -> Result<PathBuf> {
    let mut dir = std::env::current_dir()?;
    loop {
        let git = dir.join(".git");
        if git.is_dir() {
            return Ok(git.join("hooks"));
        }
        // Some setups (worktrees, submodules) make `.git` a file pointing
        // at the real gitdir.
        if git.is_file() {
            let contents = std::fs::read_to_string(&git)?;
            if let Some(gitdir) = contents.strip_prefix("gitdir: ") {
                let gitdir = PathBuf::from(gitdir.trim());
                let resolved = if gitdir.is_absolute() {
                    gitdir
                } else {
                    dir.join(gitdir)
                };
                return Ok(resolved.join("hooks"));
            }
        }
        if !dir.pop() {
            anyhow::bail!(
                "Not inside a git repository (no .git found from current directory upward)"
            );
        }
    }
}

fn install_pre_commit_hook(force: bool, strict: bool, json: bool) -> Result<()> {
    use colored::Colorize;
    use std::os::unix::fs::PermissionsExt;

    let hooks_dir = find_git_hooks_dir()?;
    std::fs::create_dir_all(&hooks_dir)?;
    let hook_path = hooks_dir.join("pre-commit");

    if hook_path.exists() && !force {
        let existing = std::fs::read_to_string(&hook_path).unwrap_or_default();
        if existing.contains("flint pre-commit hook") {
            println!(
                "{} flint pre-commit hook already installed at {}\n  Re-run with --force to overwrite (e.g. to switch modes).",
                "ℹ".blue(),
                hook_path.display()
            );
            return Ok(());
        }
        anyhow::bail!(
            "A pre-commit hook already exists at {} and was not authored by flint.\nRe-run with --force to overwrite, or move it aside first.",
            hook_path.display()
        );
    }

    let script = build_pre_commit_script(strict, json);
    std::fs::write(&hook_path, script)?;
    let mut perms = std::fs::metadata(&hook_path)?.permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(&hook_path, perms)?;

    let mode_label = match (strict, json) {
        (false, false) => "non-blocking, text",
        (false, true) => "non-blocking, JSON",
        (true, false) => "strict (blocks on errors), text",
        (true, true) => "strict (blocks on errors), JSON",
    };

    println!(
        "{} Installed flint pre-commit hook at {} ({})",
        "✓".green(),
        hook_path.display(),
        mode_label
    );
    if strict {
        println!("  • Errors block the commit; warnings/info pass through.");
        println!("  • Bypass with `git commit --no-verify`.");
    } else {
        println!("  • Diagnostics print on every commit, but the hook never blocks.");
    }
    println!("  • Remove with: flint hooks uninstall");
    Ok(())
}

fn uninstall_pre_commit_hook() -> Result<()> {
    use colored::Colorize;

    let hook_path = find_git_hooks_dir()?.join("pre-commit");
    if !hook_path.exists() {
        println!("{} No pre-commit hook found at {}", "ℹ".blue(), hook_path.display());
        return Ok(());
    }
    let contents = std::fs::read_to_string(&hook_path).unwrap_or_default();
    if !contents.contains("flint pre-commit hook") {
        anyhow::bail!(
            "Pre-commit hook at {} was not authored by flint — refusing to remove it.\nDelete it manually if intended.",
            hook_path.display()
        );
    }
    std::fs::remove_file(&hook_path)?;
    println!("{} Removed flint pre-commit hook from {}", "✓".green(), hook_path.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The hook must invoke `flint check --staged .` exactly once — per-file
    /// invocation meant the cross-file graph pass NEVER ran in hooks (it
    /// only fires from directory lints), and rename breakage was invisible.
    /// (Supersedes the older per-file regression test: `--staged` accepts a
    /// single directory, so the old xargs batching failure can't recur.)
    #[test]
    fn pre_commit_script_runs_staged_once() {
        for (strict, json) in [(false, false), (true, false), (false, true), (true, true)] {
            let script = build_pre_commit_script(strict, json);
            assert!(
                script.contains("flint check --staged"),
                "hook script (strict={strict}, json={json}) must use --staged"
            );
            assert!(
                !script.contains("while IFS= read -r f; do"),
                "hook script (strict={strict}, json={json}) must not loop per file — \
                 that skips the cross-file pass"
            );
            assert_eq!(
                script.matches("flint check").count(),
                2, // one in the comment header, one real invocation
                "hook script (strict={strict}, json={json}) should invoke flint once"
            );
        }
    }

    #[test]
    fn pre_commit_script_modes_render_distinct_banners() {
        let non_strict = build_pre_commit_script(false, false);
        let strict = build_pre_commit_script(true, false);
        assert!(non_strict.contains("warnings only, never blocks"));
        assert!(strict.contains("strict — errors will block commits"));
        assert_ne!(non_strict, strict, "modes must produce different scripts");
    }

    #[test]
    fn pre_commit_script_strict_mode_has_explicit_block_path() {
        // In strict mode the script must propagate flint's failure through
        // the marker file and emit the human-readable "errors found —
        // commit blocked" message before exiting 1.
        let strict = build_pre_commit_script(true, false);
        assert!(strict.contains("errors found — commit blocked."));
        assert!(strict.contains("exit 1"));
    }

    #[test]
    fn pre_commit_script_non_strict_never_blocks() {
        // Non-strict scripts must NEVER include `exit 1` — even if flint
        // returns an error, the marker check is a no-op.
        let non_strict = build_pre_commit_script(false, false);
        assert!(
            !non_strict.contains("exit 1"),
            "non-strict hook must not contain `exit 1` — it always passes"
        );
    }

    #[test]
    fn pre_commit_script_json_mode_passes_format_flag() {
        let json = build_pre_commit_script(false, true);
        assert!(
            json.contains("--format=json"),
            "json mode must pass --format=json to flint check"
        );
        let text = build_pre_commit_script(false, false);
        assert!(
            !text.contains("--format=json"),
            "non-json mode must not pass --format=json"
        );
    }
}
